AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ClothesRecommender

  Sample SAM Template for ClothesRecommender
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ClothesRecommenderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: clothes-recommender/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          OWM_API_KEY: !Ref OWM_API_KEY
          CITY_ID: 2179537 # Default to wellington
      Events:
        ClothesRecommender:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clothes
            Method: get

          # TODO: schedule event source object: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#schedule

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClothesRecommenderApi:
    Description: "API Gateway endpoint URL for Prod stage for Clothes Recommender function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/clothes/"
  ClothesRecommenderFunction:
    Description: "Clothes Recommender Lambda Function ARN"
    Value: !GetAtt ClothesRecommenderFunction.Arn
  ClothesRecommenderFunctionIamRole:
    Description: "Implicit IAM Role created for Clothes Recommender function"
    Value: !GetAtt ClothesRecommenderFunctionRole.Arn
